@startuml

hide stereotype
hide circle
skinparam linetype polyline
skinparam roundCorner 10






rectangle "A02BC Proton pump inhibitors" {

class "**    Rabeprazole    **" {
A02BC04    
}

class "**    Pantoprazole    **" {
A02BC02
}

class "**    Omeprazole    **" {
    A02BC01
}

class "**    Esomeprazole**    "{
A02BC05    
}

/'
package "Restricted Medication Hospital A"{
    object 1
    object 3
}

package "Restricted Medication Hospital B"{
    object "1" as 1b
    object 2
}
'/

}
@enduml